export const colors = {
  BACKGROUND: '#262830',
  TEXT: '#fff',
  PRIMARY: '#1a98c6',
  SUCCESS: '#1BC98E',
  WARNING: '#E4D836',
  DANGER: '#E64759'
};

export const appActions = {
  SET_CREDENTIALS: 'SET_CREDENTIALS',
  SET_UPLOADS: 'SET_UPLOADS',
  SET_UPLOADING: 'SET_UPLOADING',
  SET_COMPRESSING: 'SET_COMPRESSING',
  SET_UPLOAD_PERCENT: 'SET_UPLOAD_PERCENT',
  SET_COMPRESS_PERCENT: 'SET_COMPRESS_PERCENT',
};

export const localStorageKeys = {
  S3_BUCKET: 'S3_BUCKET',
  ACCESS_KEY_ID: 'ACCESS_KEY_ID',
  SECRET_ACCESS_KEY: 'SECRET_ACCESS_KEY',
  REGION: 'REGION',
  UPLOADS: 'UPLOADS'
};
